//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBFlash.AirportStats {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBFlash.AirportStats.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(function() { 
        ///	$(&quot;#dialog&quot;).dialog({ 
        ///		autoOpen: false, 
        ///		modal: false, 
        ///		position: { my: &quot;left top&quot;, at: &quot;left+150 top+40&quot;}, 
        ///		resizable: false 
        ///	});
        ///	$(&quot;#infodialog&quot;).dialog({ 
        ///		autoOpen: false, 
        ///		modal: false, 
        ///		position: { my: &quot;left top&quot;, at: &quot;left+150 top+40&quot;}, resizable: false 
        ///	});
        ///	$(&quot;.info-dialog&quot;).on(&quot;click&quot;, function(e) { 
        ///		e.preventDefault(); 
        ///		$(&quot;#infodialog&quot;).html(&quot;&quot;); 
        ///		$(&quot;#infodialog&quot;).dialog(&quot;option&quot;, &quot;title&quot;, &quot;Loading...&quot;).dialog(&quot;open&quot;); 
        ///		$(&quot;#infodialog&quot;).dia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirportStats {
            get {
                return ResourceManager.GetString("AirportStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button {
        ///	background-image: linear-gradient(#22495F, #223747); 
        ///	color: white;
        ///	border-radius: 2px;
        ///	vertical-align: middle;
        ///}
        ///.footer {
        ///	font-size: .5625em;
        ///	color: lightgray;
        ///}
        ///.infoIcon {
        ///	background-image: url(&apos;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEMAAABDCAYAAADHyrhzAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAX/SURBVHhe7ZxpqFRlGIDVzC2tQKXQLC1bpDAoJSohs6LNFkOiQsuoH9JuC2FGGS20QBQE/Qik1QrMNqPVTFoh21ejSCPN0sgWLSu155kz5/bdmTNzrzZnmds88DBnzj2Xe+e93/m28763++bNm7t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirportStats1 {
            get {
                return ResourceManager.GetString("AirportStats1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @keyframes chartjs-render-animation{from{opacity:.99}to{opacity:1}}.chartjs-render-monitor{animation:chartjs-render-animation 1ms}.chartjs-size-monitor,.chartjs-size-monitor-expand,.chartjs-size-monitor-shrink{position:absolute;direction:ltr;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1}.chartjs-size-monitor-expand&gt;div{position:absolute;width:1000000px;height:1000000px;left:0;top:0}.chartjs-size-monitor-shrink&gt;div{position:absolute;width:200%;height:200%;left [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chart_min {
            get {
                return ResourceManager.GetString("Chart_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Chart.js v2.9.3
        /// * https://www.chartjs.org
        /// * (c) 2019 Chart.js Contributors
        /// * Released under the MIT License
        /// */
        ///!function(t,e){&quot;object&quot;==typeof exports&amp;&amp;&quot;undefined&quot;!=typeof module?module.exports=e(function(){try{return require(&quot;moment&quot;)}catch(t){}}()):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;require&quot;],(function(t){return e(function(){try{return t(&quot;moment&quot;)}catch(t){}}())})):(t=t||self).Chart=e(t.moment)}(this,(function(t){&quot;use strict&quot;;t=t&amp;&amp;t.hasOwnProperty(&quot;default&quot;)?t.default:t;var e={alice [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chart_min1 {
            get {
                return ResourceManager.GetString("Chart_min1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///!function(e,t){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return t(e)}:t(e)}(&quot;undefined&quot;!=typeof window?window:this,function(C,e){&quot;use strict&quot;;var t=[],r=Object.getPrototypeOf,s=t.slice,g=t.flat?function(e){return t.flat.call(e)}:function(e){return t.concat.apply([],e)},u=t.push [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_min {
            get {
                return ResourceManager.GetString("jquery_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.12.1 - 2020-05-25
        ///* http://jqueryui.com
        ///* Includes: draggable.css, core.css, resizable.css, button.css, controlgroup.css, checkboxradio.css, dialog.css, tooltip.css, theme.css
        ///* To view and modify this theme, visit http://jqueryui.com/themeroller/?scope=&amp;folderName=base&amp;cornerRadiusShadow=8px&amp;offsetLeftShadow=0px&amp;offsetTopShadow=0px&amp;thicknessShadow=5px&amp;opacityShadow=30&amp;bgImgOpacityShadow=0&amp;bgTextureShadow=flat&amp;bgColorShadow=666666&amp;opacityOverlay=30&amp;bgImgOpacityOverlay=0&amp;bgTextureOverlay=f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_min {
            get {
                return ResourceManager.GetString("jquery_ui_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.12.1 - 2020-05-25
        ///* http://jqueryui.com
        ///* Includes: widget.js, position.js, data.js, disable-selection.js, focusable.js, form-reset-mixin.js, jquery-1-7.js, keycode.js, labels.js, scroll-parent.js, tabbable.js, unique-id.js, widgets/draggable.js, widgets/resizable.js, widgets/button.js, widgets/checkboxradio.js, widgets/controlgroup.js, widgets/dialog.js, widgets/mouse.js, widgets/tooltip.js, effect.js, effects/effect-fade.js, effects/effect-highlight.js, effects/effect-scale.js, effects/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_min1 {
            get {
                return ResourceManager.GetString("jquery_ui_min1", resourceCulture);
            }
        }
    }
}
